import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TodoBucket, { todoPostInterface } from '../components/TodoBucket'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import React, { useState } from 'react'

const portNumber = 3001 //8081 //3001
// const hostName = `172.25.0.2`
const hostName = `todo-list_server_1`

const headers = {
  // "Content-Type": "application/json; 'text/json';"
  "content-type": "application/json"
}

const Home: NextPage = ({ data }: any) => {

  const [todoListData, setTodoListData] = useState(data)

  console.log(data)

  const addNewTodo = async (inputData: todoPostInterface) => {

    const api_url = `http://localhost:8081/api/add`

    try {

      const response = await axios.post(api_url, inputData, { headers: headers })
      if (response.status === 200) {
        const resData = await fetchData("localhost", '8081')
        setTodoListData(resData)
      }
    } catch (error) {
      return error
    }
  }

  const deleteTodo = async (id: number) => {
    const api_url = `http://localhost:8081/api/delete`

    try {

      const response = await axios.post(api_url, {"todoId": id}, { headers: headers })
      if (response.status === 200) {
        const resData = await fetchData("localhost", '8081')
        setTodoListData(resData)
      }
    } catch (error) {
      return error
    }
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='font-bold text-2xl'>Todo List</h1>
      <TodoBucket todoArray={todoListData} addNewTodo={addNewTodo} deleteTodo={deleteTodo} />
    </div>
  )
}

const fetchData = async (fetchedHost: string, fetchedPort: string) => {
  const api_url = `http://${fetchedHost}:${fetchedPort}/api/view`
  try {
    const res = await fetch(api_url)
    const data = await res.json()

    return data
  } catch (error) {
    return error
  }
}

export const getServerSideProps = async () => {
  const data = await fetchData(hostName, '3001')
  return {
    props: { data }
  }
}

export default Home
